<div class="">
	<span class="title"></span>
                    <span class="controller" style="float: right;">
                        <ul>
	                        <li><a href="#">Quay lại</a></li>
                        </ul>
                    </span>
</div>
<style>
	p {
		width: 100px;
		float: left;
		margin-left: 10px;
		font-weight: bold;
	}
</style>
<div class="content" id="page">
	<form method="post">

		<br class="clear">
		<input type="hidden" name="time" value="<?php echo date('Y-m-d'); ?>">
		<p>Nội dung:</p>
		<?= Phalcon\Tag::textArea(array("comments", "cols" => 100, "rows" => 20)) ?>
		<br>
		<?= $this->tag->submitButton(array("name" => "submit", 'value' => 'Create')) ?>
	</form>
</div>