<style>
	.inputNew {
		background: url("../../images/bg_ip.png") repeat-x scroll 0 0 #ffffff;
		border: 1px solid #c0c0c0;
		color: #000000;
		font-size: 12px;
		font-weight: bold;
		margin-bottom: 0;
		margin-left: 0;
		margin-right: 0;
		margin-top: 5px !important;
		padding: 5px;
	}

	p {
		width: 100px;
		float: left;
		margin-left: 10px;
		font-weight: bold;
	}

</style>
<script>
	//    $("a").removeAttr("href");
	function add_file() {
		var sl = parseInt($(".form_product_create .add_images").attr('sl'));
		if (sl < 10) {
			sl++;
			val_radio = sl - 1;
			$(".form_product_create .add_file").append('<tr><th>' + '<p>Tên thuộc tính</p><input class="inputNew" type="input" name="keyPost[]">' + '<a class="remove">Remove</a></div>' + '</th></tr>');
			$(".form_product_create .add_images").removeAttr('sl');
			$(".form_product_create .add_images").attr('sl', '' + sl + '');
		} else {
			alert('Must be lower 10');
		}
		console.log(sl);
	}
</script>
<span class="title">Thêm thuộc tính</span>
<span class="controller" style="float: right;">
                        <ul>
	                        <li>
		                        <a href="<?php echo $url ?>users/insert<?php if (isset($roomid)) echo '/' . $roomid; ?>">Thêm</a>
	                        </li>
                        </ul>
                    </span>
</div>
<br class="clear">
<div class="content" id="page">
	<form method="post" enctype="multipart/form-data" class="form_product_create">
		<table class="tabs">
			<thead>
			<tr>
				<th><input type="button" class="add_images" sl="1" onclick="add_file()" value="Add"/></th>
				<th><input type="submit" name="submit" value="Done"></th>
			</tr>
			</thead>
			<tbody>
			<tr>
				<th>
					<div class="add_file"></div>
				</th>
			</tr>
			</tbody>
		</table>
	</form>
</div>
