<html>
<head>
	<meta content="text/html; charset=utf-8" http-equiv="Content-Type">

	<!-- Website Title -->
	<title>WeAdmin | Login</title>

	<!-- Meta data for SEO -->
	<meta content="" name="description">
	<meta content="" name="keywords">

	<!-- Template stylesheet -->
	<link media="all" type="text/css" rel="stylesheet" href="css/green/screen.css">
	<link media="all" type="text/css" rel="stylesheet" href="css/green/datepicker.css">
	<link media="all" type="text/css" rel="stylesheet" href="js/visualize/visualize.css">
	<link media="all" type="text/css" rel="stylesheet" href="js/jwysiwyg/jquery.wysiwyg.css">
	<link media="all" type="text/css" rel="stylesheet" href="js/fancybox/jquery.fancybox-1.3.0.css">

	<!--[if IE]>
	<link href="css/ie.css" rel="stylesheet" type="text/css" media="all">
	<meta http-equiv="X-UA-Compatible" content="IE=7"/>
	<![endif]-->

	<!-- Jquery and plugins -->
	<script src="js/jquery.js" type="text/javascript"></script>
	<script src="js/jquery-ui.js" type="text/javascript"></script>
	<script src="js/jquery.img.preload.js" type="text/javascript"></script>
	<script src="js/hint.js" type="text/javascript"></script>
	<script src="js/visualize/jquery.visualize.js" type="text/javascript"></script>
	<script src="js/jwysiwyg/jquery.wysiwyg.js" type="text/javascript"></script>
	<script src="js/fancybox/jquery.fancybox-1.3.0.js" type="text/javascript"></script>
	<script charset="utf-8" type="text/javascript">
		$(function () {
			// find all the input elements with title attributes
			$('input[title!=""]').hint();
			$('#login_info').click(function () {
				$(this).fadeOut('fast');
			});
		});
	</script>
</head>
<body class="login">
<?php
//print_r($usr);
//if (isset($usr)) echo 'login';
//else echo 'not';
//foreach($usr as $u){
//    echo $u->username;
//    echo $u->email;
//}
?>
<img src="<?php echo $qrcode; ?>">
<!-- Begin login window -->
<div id="login_wrapper">
	<br class="clear">
	<!-- Begin content -->
	<div id="login_body_window">
		<div class="inner">
			<?php echo Phalcon\Tag::form() ?>
			<p>
				<label for="name">UserName</label>
				<?php echo Phalcon\Tag::textField(array("username", "size" => 30)) ?>
			</p>

			<p>
				<label for="name">Password</label>
				<?php echo Phalcon\Tag::passwordField(array("password", "size" => 30)); ?>
			</p>

			<p>
				<?php echo Phalcon\Tag::submitButton(array("Login", "name" => "login")) ?>
			</p>

			</form>
		</div>
	</div>
	<!-- End content -->
</div>
<!-- End login window -->
<div id="fancybox-tmp"></div>
<div id="fancybox-loading">
	<div></div>
</div>
<div id="fancybox-overlay"></div>
<div id="fancybox-wrap">
	<div id="fancybox-outer">
		<div id="fancy-bg-n" class="fancy-bg"></div>
		<div id="fancy-bg-ne" class="fancy-bg"></div>
		<div id="fancy-bg-e" class="fancy-bg"></div>
		<div id="fancy-bg-se" class="fancy-bg"></div>
		<div id="fancy-bg-s" class="fancy-bg"></div>
		<div id="fancy-bg-sw" class="fancy-bg"></div>
		<div id="fancy-bg-w" class="fancy-bg"></div>
		<div id="fancy-bg-nw" class="fancy-bg"></div>
		<div id="fancybox-inner"></div>
		<a id="fancybox-close"></a><a id="fancybox-left" href="javascript:;"><span id="fancybox-left-ico"
		                                                                           class="fancy-ico"></span></a><a
			id="fancybox-right" href="javascript:;"><span id="fancybox-right-ico" class="fancy-ico"></span></a></div>
</div>
</body>
</html>