<div class="">
	<span class="title"></span>
                    <span class="controller" style="float: right;">
                        <ul>
	                        <li><a href="#">Quay lại</a></li>
                        </ul>
                    </span>
</div>
<style>
	p {
		width: 100px;
		float: left;
		margin-left: 10px;
		font-weight: bold;
	}
</style>
<script>
	$(function () {
		$(".datepicker_insert").datepicker();
	});
</script>
<?php

?>
<form method="post">
	<br class="clear">

	<p>Group:</p>
	<select>
		<?php foreach($groupList as $group) {?>
		<option <?php echo $group->idgroup?>><?php echo $group->name?></option>
		<?php } ?>
	</select>
	<br>

	<p>read</p>
	<input type="checkbox" name="chk[]">
	<br/>

	<p>modify</p>
	<input type="checkbox" name="chk[]">
	<br/>

	<p>delete</p>
	<input type="checkbox" name="chk[]">
	<br/>
	<?= $this->tag->submitButton(array("name" => "submit", 'value' => 'Create')) ?>
	<div class="chart_wrapper" id="chart_wrapper"></div>
	<!-- End bar chart table-->
</form>