<span class="title">List data</span>
<span class="controller" style="float: right;">
                        <ul>
	                        <li>
		                        <a href="<?php echo $url ?>users/insert<?php if (isset($roomid)) echo '/' . $roomid; ?>">Thêm</a>
	                        </li>
	                        <li><a class="del_all">Xóa</a></li>
	                        <li><a href="#">Bật</a></li>
	                        <li><a href="#">Tắt</a></li>
                        </ul>
                    </span>
</div>
<br class="clear">
<div class="content" id="page">
	<form method="post" action="" name="form_data">
		<div id="view">
			<table width="100%" cellspacing="0" cellpadding="0" class="data">
				<thead>
				<tr>
					<th>STT</th>
					<th style="width:10px">
						<input type="checkbox" name="check_all" id="check_all">
					</th>
					<th style="width:20%">Name</th>
				</tr>
				</thead>
				<?php $i=1;foreach($listCate as $cate) {?>
				<tr>
					<td><?php echo $i?></td>
					<td>
						<input type="checkbox" class="check" checkbox_id="<?php echo $cate->idcategory ?>">
					</td>
					<td><?php echo $cate->name?></td>
					<td><a href="">edit</a>
						<a del_id="<?php echo $cate->idcategory ?>" class="detele_user">delete</a></td>
				</tr>
				<?php }   $i++ ?>
				<tbody>
			</table>
		</div>
		<div class="chart_wrapper" id="chart_wrapper"></div>
		<!-- End bar chart table-->
	</form>
	<!-- End pagination -->
</div>