<span class="title">List data</span>
<br class="clear">
<div class="content" id="page">
	<form method="post" action="" name="form_data">
		<div id="view">
			<table width="100%" cellspacing="0" cellpadding="0" class="data">
				<thead>
				<tr>
					<th style="width:5%">STT</th>
					<th style="width:20%">Name</th>
				</tr>
				</thead>
				<?php $i = 1;
				foreach ($listCate as $cate) {
					?>
					<tr>
						<td><?php echo $i ?></td>
						<td>
							<a href="<?php echo $url ?>post/list/<?php echo $cate->idcategory ?>"><?php echo $cate->name ?></a>
						</td>

					</tr>
					<?php $i++;
				} ?>
				<tbody>
			</table>
		</div>
		<div class="chart_wrapper" id="chart_wrapper"></div>
	</form>
</div>