<span class="title">List data</span>
</div>
<br class="clear">
<div class="content" id="page">
	<form method="post" action="" name="form_data">
		<div id="view">
			<table width="100%" cellspacing="0" cellpadding="0" class="data">
				<thead>
				<tr>
					<th>STT</th>
					<th>Nội Dung</th>
<!--					<th>Người post</th>-->
					<th>Delete</th>
				</tr>
				</thead>
				<tbody>
				<?php $i = 1;
				foreach ($listPost as $list) { ?>
					<tr>
						<td><?php echo $i ?></td>
						<td><?php echo $list->Detail ?></td>
<!--						<td>--><?php //echo $list->fullname ?><!--</td>-->
						<td><a del_id="<?php echo $list->idpost ?>" class="detele_user">Delete</a></td>
					</tr>
					<?php $i++;
				} ?>
				</tbody>
			</table>
		</div>
		<div class="chart_wrapper" id="chart_wrapper"></div>
		<!-- End bar chart table-->
	</form>
	<!-- End pagination -->
</div>