<span class="title"></span>
<div class="">
	<span class="title"></span>
                    <span class="controller" style="float: right;">
                        <ul>
	                        <li><a href="#">Quay lại</a></li>
                        </ul>
                    </span>
</div>
<style>
	p {
		width: 100px;
		float: left;
		margin-left: 10px;
		font-weight: bold;
	}
</style>
<div class="content" id="page">
	<form method="post">
		<br class="clear">
			<p>Group</p><select name = 'group'>
			<option>Select group</option>
				<?php foreach($groupList as $list) {?>

					<option value="<?php echo $list->idgroup?>"><?php echo $list->name?></option>
				<?php } ?>
			</select>
		<br/>
		<p>Resouce</p><input type="text" name="resc">
		<br/>
		<p>Action</p><input type="text" name="action">
		<br/>
		<?= $this->tag->submitButton(array("name" => "submit", 'value' => 'Create')) ?>

	</form>
</div>