<style>
	.inputNew {
		background: url("../../images/bg_ip.png") repeat-x scroll 0 0 #ffffff;
		border: 1px solid #c0c0c0;
		color: #000000;
		font-size: 12px;
		font-weight: bold;
		margin-bottom: 0;
		margin-left: 0;
		margin-right: 0;
		margin-top: 5px !important;
		padding: 5px;
	}

	p {
		width: 100px;
		float: left;
		margin-left: 10px;
		font-weight: bold;
	}

	#xxx {
		display: none;
	}

</style>
<script>
	function add_file() {
		var sl = parseInt($(".form_product_create .add_images").attr('sl'));
		if (sl < 10) {
			sl++;
			val_radio = sl;
			$(".form_product_create .add_file").append('<input type="file">'+'<a class="'+val_radio+'remove">Remove/'+'</a>');
			$(".form_product_create .add_images").removeAttr('sl');
			$(".form_product_create .add_images").attr('sl', '' + sl + '');
		} else {
			alert('Must be lower 10');
		}
	}
	$(document).ready(function () {
		$('.display').css("display", "none");
		$('.file').val($(this).is(':checked'));

		$('.file').change(function () {
			if ($(this).is(":checked")) {
				var chk = $(this).attr('id');
				$('#' + chk + 'showFile').show();
//				var returnVal = confirm("Are you sure?");
			}
			$('.' + chk + 'remove').live("click", function () {
				alert();
				$('.' + chk + 'remove').hide();
			});
		});
	});
</script
<style>
	.inputNew {
		background: url("../../images/bg_ip.png") repeat-x scroll 0 0 #ffffff;
		border: 1px solid #c0c0c0;
		color: #000000;
		font-size: 12px;
		font-weight: bold;
		margin-bottom: 0;
		margin-left: 0;
		margin-right: 0;
		margin-top: 5px !important;
		padding: 5px;
	}

	p {
		width: 100px;
		float: left;
		margin-left: 10px;
		font-weight: bold;
	}

	.checkbox {
		display: none;
	}
</style>
<script>

</script>
<?php if(count($listAttr)) {?>
	<span class="title">List data</span>
	<span class="controller" style="float: right;">
                    </span>
	</div>
	<br class="clear">
	<div class="content" id="page">
		<form method="post" action="" name="form_data" class="form_product_create" enctype="multipart/form-data">
			<div id="view">
				<table width="100%" cellspacing="0" cellpadding="0" class="data">
					<thead>
					<tr>
						<?php foreach ($listAttr as $list) { ?>
							<th style="width:20%"><?php echo $list->name ?></th>
						<?php } ?>
					</tr>
					</thead>
					<tbody>
					<tr>
						<?php foreach ($listAttr as $list) { ?>
							<td class="tdFirst" id="<?php echo 'td' . $list->idkey; ?>">
								<a class="add_images"
								   filename= <?php echo $list->name ?> id="images-<?php echo $list->idkey;; ?>" sl="1"
								   rel="<?php echo $list->idkey; ?>">Add
									File ||</a>

								<a class="add_text"
								   filename= <?php echo $list->name ?> id="images-<?php echo $list->idkey;; ?>" sl="1"
								   rel="<?php echo $list->idkey; ?>">Add
									Text</a>
							</td>
						<?php } ?>
					</tr>
					<tr>
						<?php foreach ($listAttr as $list) { ?>
							<td>
								<div class="display" id="<?php echo $list->idkey; ?>showFile"
								     rel="<?php echo $list->idkey; ?>">
									<div class="add_file<?php echo $list->idkey; ?>"></div>
									<div class="add_text<?php echo $list->idkey; ?>"></div>
								</div>
							</td>
						<?php } ?>
					</tr>
					</tbody>
				</table>
				<?= $this->tag->submitButton(array("name" => "submit", 'value' => 'Done')) ?>
			</div>
		</form>
	</div>
<?php } else echo 'NO DATA' ;?>
